plugins {
    id 'com.android.application'
}

android {
    namespace 'com.youtube.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.youtube.app"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
        resConfigs "en"
    }

    signingConfigs {
        release {
            storeFile file("../youtube-release.jks")
            storePassword "youtube123"
            keyAlias "youtube-key"
            keyPassword "youtube123"
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
